### ISSUE TITLE
Unexpected exception error when trying to log into Lifetime

### ISSUE THREAD

**Issue by saxainden** [GuyLewin/home-assistant-lifetime-fitness#2]
Just after installing the lifetime hacs plugin and I try to enter my username/password(verified on the lifetime website)
I get these 2 errors:
Error 1:
Logger: custom_components.lifetime_fitness.config_flow
Source: custom_components/lifetime_fitness/config_flow.py:96
integration: lifetime_fitness ([documentation](https://github.com/GuyLewin/home-assistant-lifetime-fitness), [issues](https://github.com/GuyLewin/home-assistant-lifetime-fitness/issues))
First occurred: 11:39:12 PM (1 occurrences)
Last logged: 11:39:12 PM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/lifetime_fitness/api.py", line 79, in authenticate
    response_json = await response.json()
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 80, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1243, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 406, message='Attempt to decode JSON with unexpected mimetype: ', url='https://api.lifetimefitness.com/auth/v2/login'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/lifetime_fitness/config_flow.py", line 96, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lifetime_fitness/config_flow.py", line 44, in validate_input
    await api_client.authenticate()
  File "/config/custom_components/lifetime_fitness/api.py", line 85, in authenticate
    raise ApiUnknownAuthError
custom_components.lifetime_fitness.api.ApiUnknownAuthError

Error 2:
Logger: custom_components.lifetime_fitness.api
Source: custom_components/lifetime_fitness/api.py:84
integration: lifetime_fitness ([documentation](https://github.com/GuyLewin/home-assistant-lifetime-fitness), [issues](https://github.com/GuyLewin/home-assistant-lifetime-fitness/issues))
First occurred: 11:39:12 PM (1 occurrences)
Last logged: 11:39:12 PM

Received unknown status code in authentication response: 406

**Comment by GuyLewin** [comment]
Hey I'm not actually a member of lifetime fitness anymore :) If you find a fix feel free to submit a PR!

**Comment by jsheputis** [comment]
Accidentally stumbled upon this repo after noticing an app outage at LF. Never thought about integrating their data into HA. If I get some free time I might fork/re-create this for myself (and whoever) if that's all good with you @GuyLewin

**Comment by GuyLewin** [comment]
Yeah feel free to fork if you have the time!

**Comment by jsheputis** [comment]
> Yeah feel free to fork if you have the time!

Sounds good! I'd look into it now but... as I mentioned... their APIs are having an outage so not a great time to try and mess with integration lol. Only bothered peeking at their APIs after a fellow member was asking my group if others were having login issues lol. Great idea on the integration and initial concept!

**Comment by saxainden** [comment]
> > Yeah feel free to fork if you have the time!
> 
> Sounds good! I'd look into it now but... as I mentioned... their APIs are having an outage so not a great time to try and mess with integration lol. Only bothered peeking at their APIs after a fellow member was asking my group if others were having login issues lol. Great idea on the integration and initial concept!

Thanks for looking at this! Would love to have this working!

**Comment by jsheputis** [comment]
@GuyLewin I forked and detached from this upstream as it seems abandoned.

@saxainden I did some quick brute force fixes in [this repo](https://github.com/jsheputis/home-assistant-lifetime-fitness) if you want to add it as a custom repo for now and utilize version `1.2.1`.

**Comment by jsheputis** [comment]
@GuyLewin Would you be willing to remove your integration from the defaults and I'll submit mine afterward since this repo seems abandoned? 

https://www.hacs.xyz/docs/publish/remove/

**Comment by saxainden** [comment]
> [@GuyLewin](https://github.com/GuyLewin) I forked and detached from this upstream as it seems abandoned.
> 
> [@saxainden](https://github.com/saxainden) I did some quick brute force fixes in [this repo](https://github.com/jsheputis/home-assistant-lifetime-fitness) if you want to add it as a custom repo for now and utilize version `1.2.1`.

Thanks! it works great!  Sorry I just saw this. I need to check notifications from github :)

If you want me to test anything let me know!

**Comment by GuyLewin** [comment]
Thanks @jsheputis !
